image:
  file: .gitpod.Dockerfile

ports:
  - port: 1337
    name: Backend
    visibility: public
  - port: 3000
    name: Frontend
    visibility: public
  - port: 8080
    name: Adminer
    visibility: public

tasks:
  - name: "husky"
    command: npx husky install
  - name: "database"
    command: docker-compose -f docker-compose.db.yaml up
  - name: "backend"
    init: cd backend && npm i
    command: npm run develop
  - name: "frontend"
    init: cd frontend && npm i

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - dsznajder.es7-react-js-snippets
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - chakrounanas.turbo-console-log
    - hbenl.vscode-test-explorer
