version: "3.7"

services:
  db:
    extends:
      file: ./db/docker-compose.postgres.yaml
      service: postgres
    networks:
      - sps_db_network

  frontend:
    extends:
      file: ./frontend/docker-compose.frontend.yaml
      service: frontend
    networks:
      - sps_db_network
    ports:
      - 3000:3000

  backend:
    extends:
      file: ./backend/docker-compose.backend.yaml
      service: backend
    networks:
      - sps_db_network
    environment:
      DATABASE_HOST: db
    ports:
      - 1337:1337

networks:
  sps_db_network:
    external: false
    name: sps_db_network
