version: "3.7"

services:
  backend:
    extends:
      file: ./docker-compose.backend.yaml
      service: backend
    environment:
      DATABASE_HOST: db
    networks:
      - sps_db_network
    ports:
      - 1337:1337

networks:
  sps_db_network:
    external: true
