version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: develop.Dockerfile
    restart: always
    environment:
      DATABASE_HOST: db
    volumes:
      - .:/usr/src/app
    expose:
      - 1337
