version: "3.7"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
      - 443:443
    command:
      - --log.level=DEBUG
      - --api
      - --providers.docker.swarmmode
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - ./certs/:/certs/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        # Redirect to HTTPS
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
        - traefik.http.routers.redirs.entrypoints=web
        - traefik.http.routers.redirs.middlewares=redirect-to-https
        # Dashboard
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.middlewares=admin
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.rule=Host(`traefik.yourstartup.com`)
        - traefik.http.middlewares.admin.basicauth.users=code:XXXXXXXXXXXXXXXXXXXXXXXXX
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.docker.network=traefik_overlay

networks:
  traefik_overlay:
    external: false
    attachable: true
