version: "3.7"

services:
  sps_frontend:
    image: singlepagestartup/sps_lite_frontend
    # image: registry.hub.docker.com/your_dockerhub_username/sps_frontend:0.0.1
    networks:
      - traefik_overlay
    command: "sh -c './build-start.sh'"
    # command: "sh -c './start.sh'"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.services.sps_frontend.loadbalancer.server.port=3000
        - traefik.http.routers.sps_frontend.entrypoints=websecure
        - traefik.http.routers.sps_frontend.tls=true
        - traefik.http.routers.sps_frontend.rule=Host(`yourstartup.com`)
        - traefik.docker.network=traefik_overlay

networks:
  traefik_overlay:
    external: true
