version: "3.7"

services:
  sps_backend:
    image: singlepagestartup/sps_lite_backend
    # image: registry.hub.docker.com/your_dockerhub_username/sps_backend:0.0.1
    networks:
      - traefik_overlay
    # If you want to store uploads localy
    volumes:
      - ./sps_backend_uploads:/usr/src/app/public/uploads
    # Place all environment variables in a file called sps-lite.env
    env_file:
      - ./sps-lite.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1337
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.services.sps_backend.loadbalancer.server.port=1337
        - traefik.http.routers.sps_backend.entrypoints=websecure
        - traefik.http.routers.sps_backend.tls=true
        - traefik.http.routers.sps_backend.rule=Host(`api.yourstartup.com`)
        - traefik.docker.network=traefik_overlay

networks:
  traefik_overlay:
    external: true
