version: "3.7"

services:
  db:
    extends:
      file: ./docker-compose.postgres.yaml
      service: postgres
    networks:
      - sps-db-network

  adminer:
    extends:
      file: ./docker-compose.adminer.yaml
      service: adminer
    networks:
      - sps-db-network

networks:
  sps-db-network:
    external: false
    name: ${COMPOSE_PROJECT_NAME}-db-network
