version: "3.7"

services:
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    restart: always
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - ${ADMINER_PORT}:8080
