name: Env
on:
  pull_request:
    types: [closed]

jobs:
  server:
    if: contains(github.ref_name, 'ansible') && github.event.pull_request.merged == true
    uses: ./.github/workflows/ansible.yml
    secrets: inherit
    with:
      BRANCH: ${{ github.ref_name }}
