name: Deploy project to internetcomputer
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    types: [closed]
    branches:
      - deploy-to-icp

jobs:
  build-frontend-with-backend-data:
    timeout-minutes: 25
    name: Run backend and frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run backend
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_ACCESS_KET: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: |
          cd backend
          npm i
          npm run build
          cp .env.icp .env
          npm run start &
      - name: Make scripts files executable
        run: |
          chmod +x \
          ./wait-for-seeed.sh \
          ./frontend/icp-pass-envs-to-files.sh \
          ./frontend/icp-import-identity.sh \
          ./frontend/icp-update-canister.sh
      - name: Run frontend
        env:
          ICP_DEPLOYER_WALLET: ${{ secrets.ICP_DEPLOYER_WALLET }}
          ICP_DEPLOYER_KEY: ${{ secrets.ICP_DEPLOYER_KEY }}
        run: |
          ./wait-for-seeed.sh
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
          cd frontend
          ./icp-pass-envs-to-files.sh
          ./icp-import-identity.sh
          npm i
          ./icp-update-canister.sh
