name: Create frontend and backend release

on:
  release:
    types:
      - released

jobs:
  update-backend:
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      TAG: ${{ github.event.release.tag_name }}
      PRERELEASE: ${{ github.event.release.prerelease }}

  fill-database-with-seed-data:
    uses: ./.github/workflows/database.yml
    secrets: inherit
    needs:
      - update-backend

  update-frontend:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    needs:
      - fill-database-with-seed-data
    with:
      SLEEP_TIME: 360
      TAG: ${{ github.event.release.tag_name }}
      PRERELEASE: ${{ github.event.release.prerelease }}

  update-documentation:
    uses: ./.github/workflows/documentation.yml
    secrets: inherit
    with:
      TAG: ${{ github.event.release.tag_name }}
      PRERELEASE: ${{ github.event.release.prerelease }}
