name: Update frontend

on:
  pull_request:
    types: [closed]
    branches:
      - update-frontend

jobs:
  update-frontend:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    with:
      SLEEP_TIME: 0
      TAG: ${{ github.sha }}
      PRERELEASE: false
